name: ✨ Feature Request
description: Suggest a new feature or enhancement for Chess Vector Engine
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please help us understand your idea by filling out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: tier
    attributes:
      label: Target Feature Tier
      description: Which tier should this feature target?
      options:
        - Open Source (free)
        - Premium (paid)
        - Enterprise (custom)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints?
      placeholder: This should integrate with... / Performance requirements...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to contribute code for this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: By submitting this feature request, you confirm that:
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true